development:
  adapter: postgresql
  encoding: utf8
  database: pizza
  username: chefadmin
  password: hu8jmn3
  host: 127.0.0.1
  pools: 5
test:
  adapter: postgresql
  encoding: utf8
  database: pizza_test
  username: chefadmin
  password: hu8jmn3
  host: 127.0.0.1
  pools: 5